/*
 * Generated by the Jasper component of Apache Tomcat
<<<<<<< HEAD
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-10-11 09:15:21 UTC
=======
 * Version: Apache Tomcat/8.0.43
<<<<<<< HEAD
 * Generated at: 2018-10-15 06:19:10 UTC
=======
 * Generated at: 2018-10-14 15:45:06 UTC
>>>>>>> 2d2efe340d4322cb86786edb71f3f28e9ecb6762
>>>>>>> a94b76b6aa5f6e5ea3aaceefd24a836f8db2a2f6
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/ijeongsu/Desktop/IBK/GitRepository/TeamProject/EclipseWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITEP/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/ijeongsu/Desktop/IBK/GitRepository/TeamProject/EclipseWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITEP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1498801091000L));
    _jspx_dependants.put("jar:file:/Users/ijeongsu/Desktop/IBK/GitRepository/TeamProject/EclipseWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITEP/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

<<<<<<< HEAD
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n");
      out.write("\t\t<title>Home</title>\r\n");
      out.write("\t\t<link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/bootstrap-3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<script src=\"");
=======
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("<!-- \t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\n");
      out.write(" -->\t\t<meta name=\"description\" content=\"\">\n");
      out.write("\t\t<meta name=\"author\" content=\"\">\n");
      out.write("\t\t\n");
      out.write("\t    <title >IT그룹 교육 포탈</title>\n");
      out.write("\t    \n");
      out.write(" \t\t<script src=\"");
>>>>>>> 2d2efe340d4322cb86786edb71f3f28e9ecb6762
      out.print(application.getContextPath());
      out.write("/resources/jquery/jquery-3.2.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(application.getContextPath());
<<<<<<< HEAD
      out.write("/resources/bootstrap-3.3.7/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_info.emn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_info.emm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" Logined page</h4>\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
=======
      out.write("/resources/bootstrap-3.3.7/js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\t<link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/css/style.css\" rel=\"stylesheet\">\n");
      out.write("  \t\t<link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/color/default.css\" rel=\"stylesheet\">\n");
      out.write(" \t\t\n");
      out.write("\t\t    <!-- Bootstrap core CSS -->\n");
      out.write("     \t<link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\t\t\n");
      out.write("\t    <!-- Custom fonts for this template -->\n");
      out.write("\t    <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("\t    <!-- Plugin CSS -->\n");
      out.write("\t    <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/vendor/magnific-popup/magnific-popup.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\t\n");
      out.write("\t    <!-- Custom styles for this template -->\n");
      out.write("\t    <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/css/freelancer.min.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    \t<link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/css/hannafont.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    \n");
      out.write("  <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/css/nivo-lightbox.css\" rel=\"stylesheet\" />\n");
      out.write("  <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/css/nivo-lightbox-theme/default/default.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("  <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/css/owl.carousel.css\" rel=\"stylesheet\" media=\"screen\" />\n");
      out.write("  <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/css/owl.theme.css\" rel=\"stylesheet\" media=\"screen\" />\n");
      out.write("  <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/css/style.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/color/default.css\" rel=\"stylesheet\">\n");
      out.write("    \t\n");
      out.write("    \t\n");
      out.write("    \t<style type=\"text/css\">\n");
      out.write("    \t.container {\n");
      out.write(" \t\t\t width: 1120px;\n");
      out.write("  \t\t\tmax-width: none !important;\n");
      out.write("/*   \t\t\tmim-width: 1120px !important;\n");
      out.write(" */  \t\t\t\n");
      out.write(" \t\t}\n");
      out.write(" \n");
      out.write("\t\t\t.hidden { \n");
      out.write("\t\t\tdisplay: inline-block; \n");
      out.write("\t\t\twidth: 200px; \n");
      out.write("\t\t\twhite-space:nowrap;\n");
      out.write("\t\t\t overflow: hidden;\n");
      out.write("\t\t\t  text-overflow: ellipsis; \n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t }\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\n");
      out.write("    \t</style>\n");
      out.write("    \t\n");
      out.write("    \t<script>\n");
      out.write("    \t\t// 관리자만 보이게    \t\t\n");
      out.write("\t\t\t$(function() {\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_info.auth_cd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" !='04'){\n");
      out.write("\t\t\t\t\t$(\"#adminButton\").attr('style', 'visiblity:show');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("    \t\t\n");
      out.write("    \t</script>\n");
      out.write("    \t\n");
      out.write("\t</head>\n");
      out.write("<body id=\"page-top\">\n");
      out.write("\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav class=\"navbar navbar-expand bg-secondary fixed-top text-uppercase\" id=\"mainNav\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <a class=\"hanna navbar-brand js-scroll-trigger\" href=\"#page-top\">IBK 교육 포탈</a>\n");
      out.write("\n");
      out.write("        <div class=\" \" id=\"\">\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\n");
      out.write("          \t<li class=\"nav-item mx-0 mx-sm-1\">\n");
      out.write("              <a id='adminButton' style=\"visibility: hidden;\" class=\"hanna nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#contact\">관리자</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item mx-0 mx-sm-1\">\n");
      out.write("              <a class=\"hanna nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#portfolio\">교육 정보</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item mx-0 mx-sm-1\">\n");
      out.write("              <a class=\"hanna nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#about\">내 정보</a>\n");
      out.write("            </li>\n");
      out.write("            \n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Header -->\n");
      out.write("    <header class=\"masthead text-white text-center\" style=\"background-color: #5098ba; margin-top: 50px;\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("      \n");
      out.write("      \t<div>\n");
      out.write("      \t\n");
      out.write("      \t\t<h1 class=\"hanna animated fadeInLeftBig\" style=\"font-size: 180px; margin-bottom: 90px; z-index: 5\" >공부 의지가</h1>\n");
      out.write("      \t</div>\n");
      out.write("      \t<div>\n");
      out.write("      \t\n");
      out.write("      \t\t<h1 class=\"hanna animated fadeInRightBig\" style=\"font-size: 180px; margin-bottom: 60px; z-index: 5\">불타 오른다</h1>\n");
      out.write("      \t\n");
      out.write("      \t</div>\n");
      out.write("      \t<div class=\"animated fadeInUp\" >\n");
      out.write("      \t\t<h2 class=\"hanna\" style=\" display:inline ;\"  >- 불타서 사라짐 -</h2>\n");
      out.write("      \t\t<img style = \"position: absolute; top : -250px ;  width: 300px; opacity : 0.3 ; z-index: 1\" src=\"resources/main_page_resource/img/book.png\" alt=\"\">\n");
      out.write("      \t\t\n");
      out.write("      \t</div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <!-- Portfolio Grid Section -->\n");
      out.write("    <section class=\"portfolio\" id=\"portfolio\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <h2 class=\"hanna text-center text-uppercase text-secondary mb-0\">교육 정보</h2>\n");
      out.write("        <hr class=\"star-dark mb-5\">\n");
      out.write("        \n");
      out.write("        <h3 class=\"hanna text-uppercase text-secondary mb-0\">인기 교육 Top 8</h3>\n");
      out.write("        \n");
      out.write("\t      <div class=\"row\">\n");
      out.write("\t        <div class=\"col-xl-12\">\n");
      out.write("\t          <div class=\"\">\n");
      out.write("\t            <div id=\"owl-works\" class=\"\">\n");
      out.write("\t            \t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /WEB-INF/views/home.jsp(140,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("d");
        // /WEB-INF/views/home.jsp(140,14) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(140,14) '${top8List}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${top8List}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /WEB-INF/views/home.jsp(140,14) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVarStatus("status");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("\t              \t\t<div class=\"\">\n");
              out.write("\t              \t\t\t<a href=\"img/works/1.jpg\" title=\"This is an image title\" data-lightbox-gallery=\"gallery1\" data-lightbox-hidpi=\"resources/main_page_resource/sub/img/works/1@2x.jpg\">\n");
              out.write("\t         \t       \t\t\t<h4 class=\"hanna text-center mb-0\" >");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.rownum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("위</h4>\n");
              out.write("\t              \t\t\t\t<div style=\"text-align: center;  \"><img src=\"");
              out.print(application.getContextPath());
              out.write("/file?svr_img_file_nm=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.svr_img_file_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("&mfiletype=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.img_file_type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" class=\"photo3\" alt=\"img\"></div>\n");
              out.write("\t              \t\t\t\t<div style=\"text-align: center;  \"><h4 class=\"hanna  text-secondary hidden text-center\" style=\"padding-bottom: 0px\" >");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.course_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(" </h4></div>\n");
              out.write("\t              \t\t\t\t<div style=\"text-align: center;  \"><p class=\"hanna  text-secondary hidden text-center\" style=\"padding: 0px\" >");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.org_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</p></div>\n");
              out.write("\t              \t\t\t\t<div style=\"text-align: center;  \"><p class=\"hanna  text-secondary hidden text-center\" style=\"padding-top: 0px\" >");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.edu_st_dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(' ');
              out.write('~');
              out.write(' ');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.edu_ed_dt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</p></div>\n");
              out.write("\t              \t\t\t</a>\n");
              out.write("\t              \t\t</div>\n");
              out.write("\t              \t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\n");
      out.write("\t                           \n");
      out.write("\t            </div>\n");
      out.write("\t          </div>\n");
      out.write("\t        </div>\n");
      out.write("\t      </div>  \n");
      out.write("\t      \n");
      out.write("\t     <h3 class=\"hanna text-uppercase text-secondary mb-0\">신청 마감 임박!!</h3>\n");
      out.write("\t      <div class=\"row\">\n");
      out.write("\t        <div class=\"col-xl-12\">\n");
      out.write("\t          <div class=\"\">\n");
      out.write("\t            <div id=\"owl-works\" class=\"\">\n");
      out.write("\t            \t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f1_reused = false;
      try {
        _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f1.setParent(null);
        // /WEB-INF/views/home.jsp(162,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f1.setVar("d");
        // /WEB-INF/views/home.jsp(162,14) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(162,14) '${ddayList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ddayList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /WEB-INF/views/home.jsp(162,14) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f1.setVarStatus("status");
        int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
          if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("\t              \t\t<div class=\"\">\n");
              out.write("\t              \t\t\t<a href=\"img/works/1.jpg\" title=\"This is an image title\" data-lightbox-gallery=\"gallery1\" data-lightbox-hidpi=\"resources/main_page_resource/sub/img/works/1@2x.jpg\">\n");
              out.write("\t         \t       \t\t\t<h4 class=\"hanna text-center mb-0\" >D-");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.dday }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</h4>\n");
              out.write("\t              \t\t\t\t<div style=\"text-align: center;  \"><img src=\"");
              out.print(application.getContextPath());
              out.write("/file?svr_img_file_nm=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.svr_img_file_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("&mfiletype=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.img_file_type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" class=\"photo3\" alt=\"img\"></div>\n");
              out.write("\t              \t\t\t\t<div style=\"text-align: center;  \"><h4 class=\"hanna  text-secondary hidden text-center\" style=\"padding-bottom: 0px\" >");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.course_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(" </h4></div>\n");
              out.write("\t              \t\t\t\t<div style=\"text-align: center;  \"><p class=\"hanna  text-secondary hidden text-center\" style=\"padding: 0px\" >");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.org_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</p></div>\n");
              out.write("\t              \t\t\t\t<div style=\"text-align: center;  \"><p class=\"hanna  text-secondary hidden text-center\" style=\"padding-top: 0px\" >");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.edu_st_dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(' ');
              out.write('~');
              out.write(' ');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.edu_ed_dt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</p></div>\n");
              out.write("\t              \t\t\t</a>\n");
              out.write("\t              \t\t</div>\n");
              out.write("\t              \t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f1.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
        _jspx_th_c_005fforEach_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
      }
      out.write("            \n");
      out.write("\t            </div>\n");
      out.write("\t          </div>\n");
      out.write("\t        </div>\n");
      out.write("\t      </div>\n");
      out.write("\t      \n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("    <!-- About Section -->\n");
      out.write("    <section class=\"bg-primary text-white mb-0\" id=\"about\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <h2 class=\"text-center text-uppercase text-white\">About</h2>\n");
      out.write("        <hr class=\"star-light mb-5\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("   \n");
      out.write("          <div class=\"col-lg-4 ml-auto\">\n");
      out.write("          \n");
      out.write("            <p class=\"lead\">Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-4 mr-auto\">\n");
      out.write("            <p class=\"lead\">Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"text-center mt-4\">\n");
      out.write("          <a class=\"btn btn-xl btn-outline-light\" href=\"#\">\n");
      out.write("            <i class=\"fas fa-download mr-2\"></i>\n");
      out.write("            Download Now!\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Contact Section -->\n");
      out.write("    <section id=\"contact\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <h2 class=\"text-center text-uppercase text-secondary mb-0\">Contact Me</h2>\n");
      out.write("        <hr class=\"star-dark mb-5\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-lg-8 mx-auto\">\n");
      out.write("            <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->\n");
      out.write("            <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->\n");
      out.write("            <form name=\"sentMessage\" id=\"contactForm\" novalidate=\"novalidate\">\n");
      out.write("              <div class=\"control-group\">\n");
      out.write("                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\n");
      out.write("                  <label>Name</label>\n");
      out.write("                  <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Name\" required=\"required\" data-validation-required-message=\"Please enter your name.\">\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"control-group\">\n");
      out.write("                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\n");
      out.write("                  <label>Email Address</label>\n");
      out.write("                  <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Email Address\" required=\"required\" data-validation-required-message=\"Please enter your email address.\">\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"control-group\">\n");
      out.write("                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\n");
      out.write("                  <label>Phone Number</label>\n");
      out.write("                  <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Phone Number\" required=\"required\" data-validation-required-message=\"Please enter your phone number.\">\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"control-group\">\n");
      out.write("                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\n");
      out.write("                  <label>Message</label>\n");
      out.write("                  <textarea class=\"form-control\" id=\"message\" rows=\"5\" placeholder=\"Message\" required=\"required\" data-validation-required-message=\"Please enter a message.\"></textarea>\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <br>\n");
      out.write("              <div id=\"success\"></div>\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-xl\" id=\"sendMessageButton\">Send</button>\n");
      out.write("              </div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"footer text-center\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-4 mb-5 mb-lg-0\">\n");
      out.write("            <h4 class=\"text-uppercase mb-4\">Location</h4>\n");
      out.write("            <p class=\"lead mb-0\">2215 John Daniel Drive\n");
      out.write("              <br>Clark, MO 65243</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-4 mb-5 mb-lg-0\">\n");
      out.write("            <h4 class=\"text-uppercase mb-4\">Around the Web</h4>\n");
      out.write("            <ul class=\"list-inline mb-0\">\n");
      out.write("              <li class=\"list-inline-item\">\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\n");
      out.write("                  <i class=\"fab fa-fw fa-facebook-f\"></i>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list-inline-item\">\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\n");
      out.write("                  <i class=\"fab fa-fw fa-google-plus-g\"></i>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list-inline-item\">\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\n");
      out.write("                  <i class=\"fab fa-fw fa-twitter\"></i>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list-inline-item\">\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\n");
      out.write("                  <i class=\"fab fa-fw fa-linkedin-in\"></i>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list-inline-item\">\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\n");
      out.write("                  <i class=\"fab fa-fw fa-dribbble\"></i>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-4\">\n");
      out.write("            <h4 class=\"text-uppercase mb-4\">About Freelancer</h4>\n");
      out.write("            <p class=\"lead mb-0\">Freelance is a free to use, open source Bootstrap theme created by\n");
      out.write("              <a href=\"http://startbootstrap.com\">Start Bootstrap</a>.</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <div class=\"copyright py-4 text-center text-white\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <small>Copyright &copy; Your Website 2018</small>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->\n");
      out.write("    <div class=\"scroll-to-top d-lg-none position-fixed \">\n");
      out.write("      <a class=\"js-scroll-trigger d-block text-center text-white rounded\" href=\"#page-top\">\n");
      out.write("        <i class=\"fa fa-chevron-up\"></i>\n");
      out.write("      </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Portfolio Modals -->\n");
      out.write("\n");
      out.write("    <!-- Portfolio Modal 1 -->\n");
      out.write("    <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-1\">\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\n");
      out.write("              <hr class=\"star-dark mb-5\">\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/portfolio/cabin.png\" alt=\"\">\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("                <i class=\"fa fa-close\"></i>\n");
      out.write("                Close Project</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Portfolio Modal 2 -->\n");
      out.write("    <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-2\">\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\n");
      out.write("              <hr class=\"star-dark mb-5\">\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/portfolio/cake.png\" alt=\"\">\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("                <i class=\"fa fa-close\"></i>\n");
      out.write("                Close Project</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Portfolio Modal 3 -->\n");
      out.write("    <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-3\">\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\n");
      out.write("              <hr class=\"star-dark mb-5\">\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/portfolio/circus.png\" alt=\"\">\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("                <i class=\"fa fa-close\"></i>\n");
      out.write("                Close Project</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Portfolio Modal 4 -->\n");
      out.write("    <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-4\">\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\n");
      out.write("              <hr class=\"star-dark mb-5\">\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/portfolio/game.png\" alt=\"\">\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("                <i class=\"fa fa-close\"></i>\n");
      out.write("                Close Project</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Portfolio Modal 5 -->\n");
      out.write("    <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-5\">\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\n");
      out.write("              <hr class=\"star-dark mb-5\">\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/portfolio/safe.png\" alt=\"\">\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("                <i class=\"fa fa-close\"></i>\n");
      out.write("                Close Project</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Portfolio Modal 6 -->\n");
      out.write("    <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-6\">\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\n");
      out.write("              <hr class=\"star-dark mb-5\">\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/portfolio/submarine.png\" alt=\"\">\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\n");
      out.write("                <i class=\"fa fa-close\"></i>\n");
      out.write("                Close Project</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap core JavaScript -->\n");
      out.write("    <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Plugin JavaScript -->\n");
      out.write("    <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/vendor/magnific-popup/jquery.magnific-popup.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Contact Form JavaScript -->\n");
      out.write("    <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/jqBootstrapValidation.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Custom scripts for this template -->\n");
      out.write("    <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/freelancer.min.js\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/jquery.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/jquery.scrollTo.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/jquery.nav.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/jquery.localScroll.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/bootstrap.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/jquery.prettyPhoto.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/isotope.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/jquery.flexslider.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/inview.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/animate.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/js/custom.js\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/js/jquery.sticky.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/js/slippry.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/js/wow.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/js/owl.carousel.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/js/nivo-lightbox.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/main_page_resource/sub/js/custom.js\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
>>>>>>> 2d2efe340d4322cb86786edb71f3f28e9ecb6762
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
